

CREATE TABLE IF NOT EXISTS bulletins(
  id TEXT PRIMARY KEY,
  xStart INTEGER NOT NULL,
  yStart INTEGER NOT NULL,
  xEnd INTEGER NOT NULL,
  yEnd INTEGER NOT NULL,
  width INTEGER NOT NULL DEFAULT 0,
  height INTEGER NOT NULL DEFAULT 0,
  content TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS flowers(
  id TEXT PRIMARY KEY,
  x INTEGER NOT NULL,
  y INTEGER NOT NULL,
  scale FLOAT NOT NULL,
  species INTEGER NOT NULL,
  message TEXT NOT NULL,
  bulletinId TEXT NOT NULL,
  CONSTRAINT fk_bullein_flower FOREIGN KEY (bulletinId) REFERENCES bulletins(id)
);
