

CREATE TABLE IF NOT EXISTS bulletins(
  id TEXT PRIMARY KEY,
  xStart INTEGER NOT NULL,
  yStart INTEGER NOT NULL,
  xEnd INTEGER NOT NULL,
  yEnd INTEGER NOT NULL,
  width INTEGER NOT NULL DEFAULT 0,
  height INTEGER NOT NULL DEFAULT 0,
  content TEXT NOT NULL
);
